on:
  pull_request:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "Please use Japanese in descriptions."
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS:
            "Please use Japanese in descriptions and add those below existing
            descriptions, not overwrite those. Titles should not be overwritten."
          github_action.auto_review: "true"
          github_action.auto_describe: "false"
          github_action.auto_improve: "false"
